### ISSUE TITLE
v0.3 Roadmap

### ISSUE THREAD

**Issue by doyoubi** [doyoubi/undermoon#104]
The main change in v0.3 will be broker API that will break compatibility. It will be done with overmoon v0.2

- [x] [Broker API change](https://github.com/doyoubi/undermoon/issues/103)
- [x] Add version to broker api
- [x] Make `SlotRange` an arbitrary range for better migration performance.
- [x] Build `mem_broker` and make it usable.
- [x] Add a `host` field in `ProxyResource` of `mem_broker`.
- [x] Save `mem_broker` data in a file.
- [x] Add an API to bump global epoch and cluster epoch to force proxies to update their metadata.
- [x] Add a broker api to check whether the current free proxies are sufficient for any host failure.
- [x] [Support redis-cluster-proxy](https://github.com/doyoubi/undermoon/issues/86) But not fully tested
- [x] [Amend INFO command](https://github.com/doyoubi/undermoon/issues/38)
- [x] Balance masters
- [ ] Remove `{:?}` exposed to the users.
- [x] [Support some blocking commands](https://github.com/doyoubi/undermoon/issues/82)
- [x] More unit tests.
- [x] More docs.
- [x] Benchmark Graph
- [ ] Migration Time Graph
- [x] Add docs about samaritan.
- [x] Add pagination for the API getting proxy addresses.
- [ ] ~~[Compress metadata](https://github.com/doyoubi/undermoon/issues/127)~~ done in v0.5
- [x] Support Replication for memory broker
- [x] [Support dynamically change the broker address of coordinator.](https://github.com/doyoubi/undermoon/issues/15)
- [x] Add docs for config.
- [x] Support active redirection for Redis single instance clients.
- [x] Delete keys on the destination proxy during migration to make migration faster.
- [x] Need more docs on the migration.
