### ISSUE TITLE
v0.5 Road Map

### ISSUE THREAD

**Issue by doyoubi** [doyoubi/undermoon#242]
# v0.5 Road Map
While v0.4 was focusing on working with [undermoon-operator](https://github.com/doyoubi/undermoon-operator) to support undermoon in kubernetes, v0.5 will focus on accessibility for users and contributors from the open-source community.

- **Command Compatibility**
  - Support more commands
    - [x] [Add support for BZPOPMIN and BZPOPMAX](https://github.com/doyoubi/undermoon/pull/237) thanks to @cfeitong 
  - Redis Clients Campatibility Tests and Fixes
    - [ ] Python
    - [ ] Java
    - [ ] Golang
- **General Improvements**
  - Performance Optimization
    - [x] [Use state machine implementation in IO](https://github.com/doyoubi/undermoon/pull/216)
    - [x] [Support batching syscall for backend IO](https://github.com/doyoubi/undermoon/pull/236)
  - Support Large Clusters
    - [ ] [Metadata Compression](https://github.com/doyoubi/undermoon/pull/241)
- **Kubernetes Improvements**
