### ISSUE TITLE
v0.6 Road map

### ISSUE THREAD

**Issue by doyoubi** [doyoubi/undermoon#303]
Undermoon `v0.6` will come with some breaking changes and further improvements on migration during scaling.

# Data Migration
- [ ] Amend retry for locked key in importing proxy during migration.
- [ ] Use multiple futures to scan the keys for migrating proxy based on slots to fasten the migration and reduce the latency of `UMSYNC` command.
- [ ] Support new key lock that can be acquired by multiple non-del commands or del commands (which can be implemented by changing to slot lock instead of key lock and using reference counting).
- [ ] Add statistics for the performance key points in migration like lock contention count.
- [ ] Add "migrated status" for hot key in the importing proxy during migration.

# Reliability
- [ ] Implement a new checker in Golang in place of the [checker in undermoon-operator](https://github.com/doyoubi/undermoon-operator/blob/master/chaostest/check_service.py)
