### ISSUE TITLE
v0.2 Roadmap

### ISSUE THREAD

**Issue by doyoubi** [doyoubi/undermoon#69]
`Undermoon` v0.2 focuses on supporting arbitrary slot migration, whose key functionality has been done in https://github.com/doyoubi/undermoon/pull/65

There are still 2 problems need to solve:
- (1) ~~The migration speed is too slow - around 450 keys per second~~ Now 4000 keys per second, which could also be tunable.
- (2) ~~The blocking phase to ensure consistency is not implemented yet.~~

The first one needs the Redis pipeline to increase the throughput. The second one needs complex synchronization. Both of them are not easy to implement without `async` and `await`.

Thus, in v0.2 `Undermoon` will change to `futures-rs` 0.3.

### v0.2 Roadmap
- [x] Move to the new future api.
- [x] Optimize Resp by only storing the index in the data to eliminate data copy.
- [x] Let `CmdTask` support multiple commands as a single request.
- [x] Refactor api from executor to the backend sender. Make then returns a Pin<Box<Future>> for future functionality such as MGET and blocking command.
- [ ] ~~More unit tests~~. moved to v0.3
- [ ] ~~More docs~~. moved to v0.3
